#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1626937020 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: https://apps.apple.com/us/app/quotify-save-your-quotes/id1626937020 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link: https://finalbits.io/downloads/quotify/presskit.zip
  # https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Quotify # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Quickly capture quotes. Add them to your home screen to stay inspired. Share favorites with others.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Jay Hickey
your_link: https://finalbits.io
your_company: Final Bits
your_city: Seattle
email_address: quotify@finalbits.io
facebook_username:
instagram_username: jayhickey
twitter_username: jayhickey
github_username: jayhickey
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Quickly Capture Quotes
    description: Capture text and add quotes fast using the camera, voice, or keyboard.
    fontawesome_icon_name: camera

  - title: Import From Other Apps
    description: Save quotes from other apps like Twitter, Instagram, Safari, Chrome, Podcasts, and more.
    fontawesome_icon_name: download

  - title: Home Screen Widgets
    description: Add widgets to your home screen and stay inspried with quotes from your collection.
    fontawesome_icon_name: mobile-screen

  - title: Style and Share
    description: Customize and share to inspire others with built-in formating for Instagram and other social media.
    fontawesome_icon_name: share-from-square

  - title: Backup and Sync
    description: Automatic quote backup and sync across all your devices. Requires Quotify Premium.
    fontawesome_icon_name: cloud

  - title: Daily Notifications
    description: Configure daily quote notifications for inspiration. Requires Quotify Premium.
    fontawesome_icon_name: bell

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: #assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#000000"
cover_overlay_transparency: 1.0

device_color: # Set to: blue, black, yellow, coral or white.

body_background_color: "#000000"

link_color: "#007aff"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#ffffff"
feature_text_color: "#666666"

feature_icons_foreground_color: "#007aff"
feature_icons_background_color: "#363636"

social_icons_foreground_color: "#ffffff"
social_icons_background_color: "#363636"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
